#!/bin/sh
# $1 = action ('configure' or 'reconfigure')
# $2 = current-installed-version
set -e

. /usr/share/debconf/confmodule || exit
db_version 2.0
db_settitle ca-certificates-icub-org/title
db_input medium ca-certificates-icub-org/trust_icub_org || true
db_go

exit 0
